version: "2"
services:
  web:
    container_name: webProd
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    links:
      - postgres
  postgres:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pass
